"""empty message

Revision ID: 619d9ecb3d3c
Revises: b6fddfa35118
Create Date: 2020-02-19 15:34:08.650959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619d9ecb3d3c'
down_revision = 'b6fddfa35118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###
