"""empty message

Revision ID: 62739bb943ac
Revises: 619d9ecb3d3c
Create Date: 2020-02-19 15:45:18.487789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62739bb943ac'
down_revision = '619d9ecb3d3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievements', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('username', mysql.VARCHAR(length=40), nullable=True))
    # ### end Alembic commands ###
