"""empty message

Revision ID: b6fddfa35118
Revises: fe4e084af90f
Create Date: 2020-02-19 15:18:40.649515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6fddfa35118'
down_revision = 'fe4e084af90f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'achievements', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'achievements', type_='foreignkey')
    op.drop_column('achievements', 'user_id')
    # ### end Alembic commands ###
