"""empty message

Revision ID: fe4e084af90f
Revises: f288860b7ca0
Create Date: 2020-02-19 15:01:51.354887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe4e084af90f'
down_revision = 'f288860b7ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('achievement', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=40), nullable=True),
    sa.Column('reward', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('achievements')
    # ### end Alembic commands ###
